handle no translation file

diff --git a/bin/yoga b/bin/yoga
--- a/bin/yoga
+++ b/bin/yoga
@@ -18,6 +18,9 @@ LICENSE="GPL-3.0-or-later"
 OUTPUT_LICENSE="public domain"
 
 
+SPDX_TRANSLATION_FILE=./spdx-translation.json
+
+
 # TODO: use jq with raw option to get rid of "
 
 # yoga -d 20201204180707  -mtd ../sources -m britz -dd tmp/work/all-mbient-linux tmp/work/armv8a-mbient-linux tmp/work/britz-mbient-linux  -i apricot-image-ui-britz
@@ -48,6 +51,10 @@ do
             ;;
         "--meta-top-dir" | "-mtd")
             META_TOP_DIR="$2"
+            shift
+            ;;
+        "--license-translation-file" | "-ltf")
+            SPDX_TRANSLATION_FILE="$2"
             shift
             ;;
         "--dist-dir" | "-dd")
@@ -306,13 +313,19 @@ fix_json()
 fix_license_expressions()
 {
     inform2 "Fixing license expressions in JSON files"
+    if [ "${SPDX_TRANSLATION_FILE}" = "" ] 
+    then
+        inform3n "Ignoring since no SPDX translation file provided"	
+	JSON_FIXED_FILES="${FLICT_COMPONENT_JSON}"
+        echo "OK"
+	return 
+    fi
     JSON_FIXED_FILES=""
     RES=OK
     for jf in ${FLICT_COMPONENT_JSON}
     do
         jf_short=$(basename $jf)
         inform3n "$jf_short"
-        SPDX_TRANSLATION_FILE=./spdx-translation.json
         FIXED_JSON=${PERMANENT_OUT_DIR}/${PACKAGE}/$(basename $(echo $jf | sed 's,\.json,-fixed\.json,g'))
         spdx-translations.py ${SPDX_TRANSLATION_FILE} $jf > $FIXED_JSON
         #echo "spdx-translations.py ${SPDX_TRANSLATION_FILE} $jf > $FIXED_JSON"
@@ -616,8 +629,8 @@ per_package()
     case $LICENSE_INFO in
         "closed")
             echo "closed license"
-            touch ${CLOSED_PLACEHOLDER}
-            return
+ #           touch ${CLOSED_PLACEHOLDER}
+#            return
             ;;
         "mix")
             echo "mixed licenses, continuing"
@@ -795,13 +808,30 @@ error()
 
 
 
+check_config()
+{
+    # SPDX translation file
+    if [ "${SPDX_TRANSLATION_FILE}" != "" ] && [ ! -f ${SPDX_TRANSLATION_FILE} ]
+    then
+	error "Missing license translation file \"${SPDX_TRANSLATION_FILE}\""
+	exit 1
+    fi
 
+    if [ ! -x flict ]
+    then
+	error "Missing flict (FOSS License Compatibility Tool)"
+	echo 
+    fi
+    
+}
 
 
 
 #
 # MAIN
 #
+
+check_config
 
 PERMANENT_OUT_DIR=$(pwd)/${OUT_DIR}
 LOG_FILE=${PERMANENT_OUT_DIR}/$(basename $0 | sed 's,\.sh,\.log,g').log
