check flict presence (if needed)

diff --git a/bin/yoga b/bin/yoga
--- a/bin/yoga
+++ b/bin/yoga
@@ -475,7 +475,7 @@ check_license_compliance()
             TXT_REPORT=${PERMANENT_OUT_DIR}/$PACKAGE/${VERSION}/$PACKAGE-compliance.txt
             #printf " * %-${FILE_FMT_LEN}s " "$(basename $jf):"
             set -o pipefail
-            ~/.local/bin/flict --json -c $jf | tail -1 | jq '.' > ${JSON_REPORT}
+            flict --json -c $jf | tail -1 | jq '.' > ${JSON_REPORT}
             #        echo ~/.local/bin/flict --json -c $jf #| tail -1 | jq '.' > ${JSON_REPORT}
             RET=$?
             echo "$RET" > $TXT_REPORT
@@ -1022,11 +1022,16 @@ check_config()
 	exit 1
     fi
 
-    if [ ! -x flict ] && [ "${COMPATIBILITY_CHECK}" != "false" ]
+    FLICT=$(which flict)
+    if [ "${COMPATIBILITY_CHECK}" != "false" ]
     then
-	error "Missing flict (FOSS License Compatibility Tool)"
-	error "Either install flict or use the option: --no-compatibility-checks"
-        exit 2
+        :
+        if [ "${FLICT}" = "" ] || [ ! -x "${FLICT}" ] 
+        then
+	    error "Missing flict (FOSS License Compatibility Tool)"
+	    error "Either install flict or use the option: --no-compatibility-checks"
+            exit 2
+        fi
     fi
     
 }
