exit yoga if yoda can't find settings

diff --git a/bin/yoga b/bin/yoga
--- a/bin/yoga
+++ b/bin/yoga
@@ -1295,7 +1295,15 @@ then
     then
         yoda  ${VERBOSE} -i ${IMAGE} find
     else
+        set -o pipefail
         ARGS=$(yoda  ${VERBOSE} -i ${IMAGE} find | tail -1)
+        RET=$?
+        if [ $RET -ne 0 ]
+        then
+            error "Failed finding settings...."
+            exit 3
+        fi
+         
         $0 ${ARGS} --noop
     fi
     exit 0
